# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: first-linux
description: Hardened Secureblue KDE image with NVIDIA hybrid graphics for Dell G7.

base-image: ghcr.io/secureblue/kde-nvidia
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - micro
      - btop

  - type: signing
